version: '3'

volumes:
  file_storage_data:

services:
  file_storage:
    container_name: file_storage 
    # command: []
    image: docker.io/bitnami/minio:2024
    ports:
      - "${S3_CONSOLE_PORT}:9000"
      - "${S3_ADMIN_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${S3_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_DEFAULT_BUCKETS: ${S3_BUCKET_NAME}
    volumes:
      - file_storage_data:/data

  public_api:
    image: public_api
    container_name: public_api
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start_public_api"]
    env_file:
      - .env
    volumes:
      - ${PWD}/static:/static
    ports:
      - "${PUBLIC_API_PORT}:${PUBLIC_API_PORT}"
  
  schedule_worker:
    image: schedule_worker
    container_name: schedule_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start_shedule_worker"]
    env_file:
      - .env