import { ENV } from "@abstract/env";

const SITEURL_BY=ENV.get("SITEURL_BY")
const EMAIL_INFO_LOGIN = ENV.get("EMAIL_INFO_LOGIN")
const EMAILS_FROM_INFO_BY = ENV.get("EMAILS_FROM_INFO_BY")
const EMAILS_FROM_SUPPORT_BY = ENV.get("EMAILS_FROM_SUPPORT_BY")

export {SITEURL_BY, EMAIL_INFO_LOGIN, EMAILS_FROM_INFO_BY, EMAILS_FROM_SUPPORT_BY}